import type { Metadata } from "next";
import Link from "next/link";
import { CartProvider } from "@/src/context/cart";
import { CartSummary } from "@/src/components/CartSummary.client";
import localFont from "next/font/local";
import { getCartState } from "@/lib/db/cart";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cartState = await getCartState();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider initialState={cartState}>
          <div className="min-h-screen">
            <header className="bg-white shadow-sm">
              <div className="container mx-auto px-4 py-4 flex justify-between items-center">
                <Link href="/">
                  <h1 className="text-xl font-bold">Demo Store</h1>
                </Link>
                <CartSummary />
              </div>
            </header>
            <div className="min-h-screen">{children}</div>
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
